--CREATE DATABASE Minions

--USE Minions

CREATE TABLE Minions
(
	Id INTEGER PRIMARY KEY NOT NULL,
	[Name] NVARCHAR(50) NOT NULL,
	[Age] TINYINT NOT NULL
)

CREATE TABLE Towns
(
	Id INTEGER PRIMARY KEY NOT NULL,
	[Name] NVARCHAR(50) NOT NULL
)

--CREATE FOREIGN KEY WHICH IS PRIMARY KEY OF TOWNS
ALTER TABLE Minions ADD TownId INT FOREIGN KEY REFERENCES Towns(Id)
--END

INSERT INTO Towns(Id, [Name]) VALUES 
	(1, 'Sofia'),
	(2, 'Plovdiv'),
	(3, 'Varna')

--SELECT Id, [Name] FROM Towns
SELECT * FROM Towns

INSERT INTO Minions (Id, [Name], Age, TownId) VALUES
	(1, 'Kevin', 22, 1),
	(2, 'Bob', 15, 3),
	(3, 'Steward', 26, 2)

SELECT * FROM Minions

--TRUNCATE TABLE Minions

--DROP TABLE Minions
--DROP TABLE Towns

CREATE TABLE Users
(
	Id BIGINT PRIMARY KEY IDENTITY NOT NULL,
	Username VARCHAR(30) UNIQUE NOT NULL,
	[Password] VARCHAR(26) NOT NULL,
	ProfilePicture VARBINARY(MAX) CHECK (DATALENGTH(ProfilePicture) <= 900 * 1024),
	LastLoginTime DATETIME2 NOT NULL,
	IsDeleted BIT NOT NULL
)

INSERT INTO Users(Username, [Password], LastLoginTime, IsDeleted) VALUES
	('Pesho', 12345, '05.02.2020', 0),
	('Pesho1', 12345, '05.02.2020', 1),
	('Pesho2', 12345, '05.02.2020', 0),
	('Pesho3', 12345, '05.02.2020', 1)

SELECT * FROM Users 

--CHANGE NAME OF PRIMARY KEY
ALTER TABLE Users DROP CONSTRAINT [PK__Users__3214EC070C8D308A]

ALTER TABLE Users ADD CONSTRAINT PK_Users_CompositeIdUsername PRIMARY KEY(Id, Username)
--END

--CHECK IF THE PASSWORD LENGTH IS MORE OR EQUAL TO 5
ALTER TABLE Users ADD CONSTRAINT CK_Users_PasswordLength CHECK(Len([Password]) >= 5)
--END

--WHEN WE ADD USER HIS DATETIME IS DEFAULT SET TO THE CURRENT TIME
ALTER TABLE Users ADD CONSTRAINT DF_Users_LastLoginTime DEFAULT GETDATE() FOR LastLoginTime
--END

ALTER TABLE Users DROP CONSTRAINT PK_Users_CompositeIdUsername

ALTER TABLE Users ADD CONSTRAINT PK_Users_Id PRIMARY KEY(Id)

ALTER TABLE Users ADD CONSTRAINT CK_Users_UsernameLength CHECK(LEN(Username) >= 3)










CREATE DATABASE SoftUni
USE SoftUni

CREATE TABLE Towns(
	Id INT PRIMARY KEY IDENTITY,
	[Name] NVARCHAR(50) NOT NULL
)

CREATE TABLE Addresses(
	Id INT PRIMARY KEY IDENTITY,
	AddressText NVARCHAR(100) NOT NULL,
	TownId INT FOREIGN KEY REFERENCES Towns(Id) NOT NULL
)

CREATE TABLE Departments(
	Id INT PRIMARY KEY IDENTITY,
	[Name] NVARCHAR(50) NOT NULL
)

CREATE TABLE Emploees(
	Id INT PRIMARY KEY IDENTITY,
	FirstName NVARCHAR(50) NOT NULL,
	MiddleName NVARCHAR(50),
	LastName NVARCHAR(50) NOT NULL,
	JobTitle NVARCHAR(30) NOT NULL,
	DepartmentId INT FOREIGN KEY REFERENCES Departments(Id) NOT NULL,
	HireDate DATE NOT NULL,
	Salary DECIMAL(7,2) NOT NULL,
	AddressId INT FOREIGN KEY REFERENCES Addresses(Id) NOT NULL
)